FROM node:22.8.0-slim

ARG NODEMON_VERSION=3.1.7

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon@${NODEMON_VERSION}


COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

EXPOSE 3000

CMD [ "/start.sh" ]